# Generated by Django 3.2.6 on 2022-01-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0009_stu_details_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stu_details',
            name='fathers_name',
            field=models.CharField(help_text='*required', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='stu_details',
            name='mothers_name',
            field=models.CharField(help_text='*required', max_length=30, null=True),
        ),
    ]
