# Generated by Django 3.2.6 on 2022-01-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0010_auto_20220108_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=100)),
                ('Option1', models.CharField(max_length=100)),
                ('Option2', models.CharField(max_length=100)),
                ('Option3', models.CharField(max_length=100)),
                ('Option4', models.CharField(max_length=100)),
                ('Corrans', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Exam_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question1', models.CharField(max_length=100)),
                ('Option11', models.CharField(max_length=100)),
                ('Option22', models.CharField(max_length=100)),
                ('Option33', models.CharField(max_length=100)),
                ('Option44', models.CharField(max_length=100)),
                ('Corrans1', models.CharField(max_length=100)),
            ],
        ),
    ]
