# Generated by Django 3.2.6 on 2022-01-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0011_exam_exam_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question2', models.CharField(max_length=100)),
                ('Option111', models.CharField(max_length=100)),
                ('Option222', models.CharField(max_length=100)),
                ('Option333', models.CharField(max_length=100)),
                ('Option444', models.CharField(max_length=100)),
                ('Corrans2', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Exam_3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question3', models.CharField(max_length=100)),
                ('Option1111', models.CharField(max_length=100)),
                ('Option2222', models.CharField(max_length=100)),
                ('Option3333', models.CharField(max_length=100)),
                ('Option4444', models.CharField(max_length=100)),
                ('Corrans3', models.CharField(max_length=100)),
            ],
        ),
    ]
