# Generated by Django 3.2.6 on 2022-01-23 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0012_exam_2_exam_3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='job_pos',
        ),
    ]
