# Generated by Django 3.2.6 on 2022-01-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0013_delete_job_pos'),
    ]

    operations = [
        migrations.CreateModel(
            name='job_poss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(help_text='*required', max_length=30, unique=True)),
                ('username', models.CharField(help_text='*required', max_length=30)),
                ('company_name', models.CharField(help_text='*required', max_length=30)),
                ('designation', models.CharField(help_text='*required', max_length=30)),
                ('roless', models.CharField(help_text='*required', max_length=200)),
                ('salary', models.IntegerField(help_text='*required')),
                ('bond_years', models.IntegerField(help_text='*required')),
                ('perkss', models.CharField(help_text='*required', max_length=200)),
                ('information_technology', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=10)),
                ('mech', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=10)),
                ('civil', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=10)),
                ('eee', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=10)),
                ('ece', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=10)),
                ('chemical', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=10)),
                ('cse', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=10)),
            ],
        ),
    ]
