# Generated by Django 3.2.6 on 2022-01-30 09:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0015_remove_stu_details_class_10_cgpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='stu_details',
            name='class_10_percentage',
            field=models.FloatField(default=50, help_text='*required', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
    ]
