# Generated by Django 3.2.6 on 2022-02-01 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0016_stu_details_class_10_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stu_details',
            name='internship',
        ),
    ]
