# Generated by Django 3.2.6 on 2022-02-08 10:52

import django.core.validators
from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0018_auto_20220206_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comp_details',
            name='hr_phn',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='*required', max_length=10, region=None, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='stu_details',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
