# Generated by Django 3.2.6 on 2022-02-08 11:00

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0019_auto_20220208_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comp_details',
            name='hr_phn',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='*required', max_length=128, region=None),
        ),
    ]
