# Generated by Django 3.2.6 on 2022-02-10 15:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0022_auto_20220210_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comp_details',
            name='hr_phn',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,10}$')]),
        ),
        migrations.AlterField(
            model_name='stu_details',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,10}$')]),
        ),
    ]
