# Generated by Django 3.2.6 on 2022-02-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0023_auto_20220210_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stu_details',
            name='branch',
            field=models.CharField(choices=[('it', 'information_technology'), ('mech', 'mech'), ('civil', 'civil'), ('eee', 'eee'), ('ece', 'ece'), ('chem', 'chemical'), ('cse', 'cse')], max_length=10),
        ),
    ]
