# Generated by Django 3.2.6 on 2022-02-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0024_alter_stu_details_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='send_msg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(default='company id', help_text='*required', max_length=30)),
                ('job_id', models.CharField(default='job id', help_text='*required', max_length=30)),
                ('student_id', models.CharField(default='y1', help_text='enter username ex:y16it***', max_length=9)),
                ('message', models.CharField(help_text='Write something', max_length=500)),
            ],
        ),
    ]
