# Generated by Django 3.2.6 on 2022-03-13 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0025_send_msg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='send_msg',
        ),
    ]
