# Generated by Django 3.2.6 on 2022-03-28 14:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0026_delete_send_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comp_details',
            name='est_year',
            field=models.IntegerField(help_text='*required'),
        ),
        migrations.AlterField(
            model_name='stu_details',
            name='branch',
            field=models.CharField(choices=[('IT', 'Information_Technology'), ('Mech', 'Mech'), ('Civil', 'Civil'), ('EEE', 'EEE'), ('ECE', 'ECE'), ('Chem', 'Chemical'), ('CSE', 'CSE')], max_length=10),
        ),
        migrations.AlterField(
            model_name='stu_details',
            name='name',
            field=models.CharField(default='full name', help_text='*required', max_length=30, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='stu_details',
            name='place',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='stu_details',
            name='sop',
            field=models.CharField(default='statement of purpose', help_text='*required', max_length=500, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='stu_details',
            name='username',
            field=models.CharField(default='y1', help_text='enter username ex:y16it***', max_length=9, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
    ]
